env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'custom-lint'
rules:
  no-console: off
  custom-lint/method-deprecated: error
  custom-lint/class-declaration: error
  custom-lint/class-method-declaration: error
  custom-lint/function-declaration: error
  custom-lint/enum-validation: error
  custom-lint/vars-declaration: error
  custom-lint/interface-validator: error
  '@typescript-eslint/no-unused-vars': off
  consistent-return: off
  required-await: off
  eqeqeq: error
  no-unused-vars: off
